services:
  - type: web
    name: av-rental-frontend
    env: static
    buildCommand: echo "No build step needed"
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
    branch: main