services:
  - type: web
    name: av-rental-frontend
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache