services:
  - type: web
    name: av-rental-frontend
    env: static
    buildCommand: echo "Building frontend..."
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
    branch: main